---
- name: enable repos
  template:
    src: open_three-tier-app.repo
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644

- name: install postgres
  yum:
    name: postgresql-server
    state: latest

- name: enable postgres at boot
  service:
    name: postgresql
    enabled: yes
  notify:
  - start postgres

- name: Check if PostgreSQL database is initialized.
  stat:
    path: /var/lib/pgsql/data/PG_VERSION
  register: pgdata_dir_version

- name: initilize postgres
  command: postgresql-setup initdb
  when: not pgdata_dir_version.stat.exists

- name: initilize postgres some more
  command: chkconfig postgresql on
  when: not pgdata_dir_version.stat.exists
